### ISSUE TITLE
grid_num not working then values array provided

### ISSUE THREAD

**Issue by aleshacasha** [madist/react-ion-slider#1]
Hi. 
`
<IonRangeSlider
                        type="double"
                        min={denom_t[0]}
                        max={denom_t[denom_t.length - 1]}
                        from={denom_t.indexOf(this.state.f.min)}
                        to={denom_t.indexOf(this.state.f.max)}
                        values={denom_t}
                        grid
                        grid_num={8}
                    />
`

**Comment by madist** [comment]
hi !
I checked your issue. and i guess it is working when using same options of `ion-range-slider`
[grid_num example](http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html)
you can check options. ( all of `react-ion-slider`'s props depends on it )
