### ISSUE TITLE
ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by conspireagency** [madist/react-ion-slider#14]
Looks like this package depends on jQuery?

![Screenshot 2020-02-18 16 26 56](https://user-images.githubusercontent.com/29992361/74790119-8a179100-526b-11ea-917b-30d996d090be.png)

**Comment by madist** [comment]
@conspireagency yes, you're right. this component need jquery.

 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
