### ISSUE TITLE
Error 'IonRangeSlider' is not exported from 'react-ion-slider'.

### ISSUE THREAD

**Issue by tmbnh1** [madist/react-ion-slider#3]
Hi Supporter,
I installer and add react-ion-slider for my react app, 
I add this:
import { IonRangeSlider } from 'react-ion-slider';
affter I add this:
<IonRangeSlider type={'double'} min={-100} max={100} from={10} to={50} step={1} />   

And I start my app, I show this error
[code]Attempted import error: 'IonRangeSlider' is not exported from 'react-ion-slider'.[/code]

Please help me. Thank you!

**Comment by madist** [comment]
@tmbnh1  hi !
you can use like these

```
import IonRangeSlider from 'react-ion-slider'
```
