### ISSUE TITLE
ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by tmbnh1** [madist/react-ion-slider#4]
I get error when I do not include jquery in public/index.html
so it's show this error: ReferenceError: jQuery is not defined
![image](https://user-images.githubusercontent.com/2167105/67173926-7443ad80-f3ea-11e9-936f-eb95c47d4172.png)

Please help me check it.
thanks

**Comment by madist** [comment]
@tmbnh1 hello !
follow the link : http://ionden.com/a/plugins/ion.rangeSlider/start.html
u can check you need to jquery for using ion.rangeSlider ( also, react-ionslider )

**Comment by madist** [comment]
@tmbnh1 hello !
follow the link : http://ionden.com/a/plugins/ion.rangeSlider/start.html
u can check you need to jquery for using ion.rangeSlider ( also, react-ionslider )
